from machine import Pin, SPI
import framebuf
import utime
from time import ticks_us

EPD_WIDTH = 122
EPD_HEIGHT = 250

RST_PIN = 12
DC_PIN = 8
CS_PIN = 9
BUSY_PIN = 13

# Commands to control the epd driver
DRIVER_OUTPUT_SETTING = 0x01
GATE_DRIVE_SETTING = 0x03
SOURCE_DRIVE_VOLTAGE = 0x04
INIT_CODE_SETTING = 0x08
WRITE_INIT_CODE_SETTING = 0x09
READ_INITIAL_CODE_SETTING = 0x0a
BOOSTER_SOFT_START = 0x0c
DEEP_SLEEP_MODE = 0x10
DATA_ENTRY_MODE = 0x11
SW_RESET = 0x12
HV_READ_DETECT = 0x14
VCI_DETECTION = 0x15
TEMP_SENSOR_CONTROL = 0x16
WRITE_TEMP_SENSOR_REG = 0x1a
READ_TEMP_SENSOR_REG = 0x1b
WRITE_EXTERNAL_TEMP_SENSOR = 0x1c
MASTER_ACTIVATION = 0x20
DISPLAY_UPDATE_CONTROL_1 = 0x21
DISPLAY_UPDATE_CONTROL_2 = 0x22
WRITE_BW_RAM = 0x24
WRITE_RED_RAM = 0x25
READ_RAM = 0x27
VCOM_SENSE = 0x28
VCOM_SENSE_DURATION = 0x29
PROGRAM_VCOM_OTP = 0x2a
WRITE_VCOM_CONTROL = 0x2b
WRITE_VCOM = 0x2c
OTP_REG_READ = 0x2d
READ_USER_ID = 0x2e
READ_STATUS_BIT = 0x2f